### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by rene78** [rene78/Dynamic-GeoJSON-import-to-Leaflet-map#2]
- [ ] Possibility: Make subsequent requests dependend on currently selected admin level(s). E.g. If admin_level=8 is selected only search for relations with this value.
- [x] Implement code into Wikivoyage Districtifier. Before you start: Fully understand branching!
- [x] On load grey out and [blur map](https://www.youtube.com/watch?v=HZv8YHYUHTU) and show wait icon. Like that:
![image](https://user-images.githubusercontent.com/36115705/47940964-aa8fd080-deec-11e8-9cba-22a623e6888c.png)
- [x] If zoomed out too much grey out map and show text "Zoom in". See here: [Stackoverflow ](https://stackoverflow.com/questions/39338377/why-isnt-my-text-being-overlaid-over-my-leaflet-map)https://codepen.io/hkadyanji/pen/bwNLKK
- [x] Make request to overpass dependent on current zoom level of map. Example:
  - If zoom level <6: "Zoom in closer to view results!"
  - If zoom level >=6: Only search admin_level=3-6
  - If zoom level >9: Only search admin_level=7-11
  - (See [this Stackexchange question](https://gis.stackexchange.com/questions/301365/overpass-query-search-range-of-integers-not-working-for-2-digit-numbers) for working overpass query)
- [x] On subsequent clicks on "Load" make sure, that only one layer control symbol is shown
- [x] On subsequent clicks on "Load" make sure, that already shown polygons are not downloaded and put on top of the existing one. For correct overpass query see thread [Exclude elements from overpass query](https://gis.stackexchange.com/questions/300896/exclude-elements-from-overpass-query).
- [x] Hide all those points (i.e. labels in OSM). Maybe change overpass query, so that only ways of the relation are downloaded (See [this post](https://gis.stackexchange.com/a/260157)).
![image](https://user-images.githubusercontent.com/36115705/47621412-d596b080-daf7-11e8-88e0-885b7df79859.png)
